export const pinCodeData = {
  "110001": { city: "New Delhi", state: "Delhi", postOffice: "Connaught Place" },
  "110002": { city: "New Delhi", state: "Delhi", postOffice: "Parliament Street" },
  "400001": { city: "Mumbai", state: "Maharashtra", postOffice: "Fort" },
  "400002": { city: "Mumbai", state: "Maharashtra", postOffice: "Andheri East" },
  "700001": { city: "Kolkata", state: "West Bengal", postOffice: "BBD Bagh" },
  "700016": { city: "Kolkata", state: "West Bengal", postOffice: "Park Street" },
  "600001": { city: "Chennai", state: "Tamil Nadu", postOffice: "Parrys" },
  "600028": { city: "Chennai", state: "Tamil Nadu", postOffice: "Guindy" },
  "560001": { city: "Bengaluru", state: "Karnataka", postOffice: "Bangalore GPO" },
  "560002": { city: "Bengaluru", state: "Karnataka", postOffice: "Chickpet" },
  "500001": { city: "Hyderabad", state: "Telangana", postOffice: "Abids" },
  "500008": { city: "Hyderabad", state: "Telangana", postOffice: "Banjara Hills" },
  "380001": { city: "Ahmedabad", state: "Gujarat", postOffice: "Navrangpura" },
  "380009": { city: "Ahmedabad", state: "Gujarat", postOffice: "Kheda" },
  "411001": { city: "Pune", state: "Maharashtra", postOffice: "Pune City" },
  "411007": { city: "Pune", state: "Maharashtra", postOffice: "Kothrud" },
  "201001": { city: "Noida", state: "Uttar Pradesh", postOffice: "Noida Sector 15" },
  "201301": { city: "Greater Noida", state: "Uttar Pradesh", postOffice: "GN Sector Alpha" },
  "122001": { city: "Gurugram", state: "Haryana", postOffice: "Gurgaon H.O." },
  "302001": { city: "Jaipur", state: "Rajasthan", postOffice: "Jaipur GPO" },
  "682001": { city: "Kochi", state: "Kerala", postOffice: "Cochin" },
};